// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdotrnjyacgmwhmrozfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impkb3Rybmp5YWNnbXdobXJvemZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQzNjgzOTEsImV4cCI6MjA4OTk0NDM5MX0.nwCrgvnM4nh5TGBdnyVq4kgIJaEYGQYiNFil7K0y6pg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});